name: CI

on: [push, pull_request]

concurrency:
  group: ${{ github.repository }}-${{ github.event.number || github.head_ref || github.sha }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: actions/setup-go@v4
        with:
          go-version: 1.19

      - name: Build
        run: |
          make build
          tree lib/ || true
          tree include/ || true

      - name: Test examples
        run: |
          make examples

          export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:`pwd`/lib
          export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:`pwd`/lib

          ./bin/read_local
